# Generated by Django 2.1.5 on 2019-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190202_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useriwm',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users_photo/', verbose_name='Фото'),
        ),
    ]
