# Generated by Django 2.1.5 on 2019-02-02 18:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('main', '0003_auto_20190202_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='IWM',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=100, unique=True, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, upload_to='users_photo/', verbose_name='Фото')),
                ('is_parent', models.BooleanField(default=False, help_text='Укажите если Вы являетесь родителем.', verbose_name='Родитель?')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
