# Generated by Django 2.0.6 on 2018-06-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
